
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rudr'a
 */
public class Bill_View extends javax.swing.JFrame {

    /**
     * Creates new form Bill_View
     */
    public Bill_View() {
          this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        setIcon();
    }
 public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("HotelIcon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name_txt = new javax.swing.JTextField();
        Id_txt = new javax.swing.JTextField();
        mobile_txt = new javax.swing.JTextField();
        Profession_txt = new javax.swing.JTextField();
        romm_txt = new javax.swing.JComboBox<>();
        type_txt = new javax.swing.JComboBox<>();
        date_1 = new com.toedter.calendar.JDateChooser();
        date_2 = new com.toedter.calendar.JDateChooser();
        search_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        select_txt = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        Back_btn = new javax.swing.JButton();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Bill Window");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Priyanka Palace");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, 230, 30));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 3, 48)); // NOI18N
        jLabel2.setText("Check Bill");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 70));

        print.setBackground(new java.awt.Color(255, 255, 0));
        print.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 30, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Customer Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Customer ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("Mobile");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("Profession");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setText("Room");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 110, 30));

        jLabel11.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel11.setText("Check In");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("Total(INR)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 110, 30));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel10.setText("Room Type");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 110, 30));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel12.setText("Check Out");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, 110, 30));

        name_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 330, 30));

        Id_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(Id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, 160, 30));

        mobile_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(mobile_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 250, 30));

        Profession_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(Profession_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 300, 30));

        romm_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        romm_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---None---", "Single Room", "Double Room", "Family Room", "Carporate Room" }));
        getContentPane().add(romm_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 260, 30));

        type_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        type_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---None---", "AC", "Middle AC", "Non AC" }));
        getContentPane().add(type_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, 220, 30));

        date_1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        date_1.setOpaque(false);
        getContentPane().add(date_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 220, 30));

        date_2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        date_2.setOpaque(false);
        getContentPane().add(date_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 550, 220, 30));

        search_txt.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(search_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 330, 30));

        search_btn.setBackground(new java.awt.Color(0, 204, 0));
        search_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, -1, 30));

        select_txt.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        select_txt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Name", "ID" }));
        select_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_txtActionPerformed(evt);
            }
        });
        getContentPane().add(select_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 130, 30));

        total.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 620, 240, 30));

        save_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Opened Folder_48px.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.setBorder(null);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 620, 100, 30));

        Back_btn.setBackground(new java.awt.Color(51, 102, 255));
        Back_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        Back_btn.setText("Back");
        Back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 620, -1, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/497320.jpg"))); // NOI18N
        image.setText("jLabel1");
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        try
        {
            switch (select_txt.getSelectedItem().toString()) {
                case "Name":
                {
                    String sql="select * from Registration where Name=?";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,search_txt.getText());
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        String a=rs.getString("Name");
                        name_txt.setText(a);
                        String b=rs.getString("ID");
                        Id_txt.setText(b);
                        String c=rs.getString("Mobile");
                        mobile_txt.setText(c);
                        String d=rs.getString("Profession");
                        Profession_txt.setText(d);
                        String e=rs.getString("Room");
                        romm_txt.setSelectedItem(e);
                        String f=rs.getString("RoomType");
                        type_txt.setSelectedItem(f);
                        String g=rs.getString("CheckIn");
                        ((JTextField)date_1.getDateEditor().getUiComponent()).setText(g);
                        String h=rs.getString("CheckOut");
                        ((JTextField)date_2.getDateEditor().getUiComponent()).setText(h);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Sorry No Result");
                    } break;
                }
                case "ID":
                {
                    String sql="select * from Registration where ID=?";
                    pst=conn.prepareStatement(sql);
                    pst.setString(1,search_txt.getText());
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        String a=rs.getString("Name");
                        name_txt.setText(a);
                        String b=rs.getString("ID");
                        Id_txt.setText(b);
                        String c=rs.getString("Mobile");
                        mobile_txt.setText(c);
                        String d=rs.getString("Profession");
                        Profession_txt.setText(d);
                        String e=rs.getString("Room");
                        romm_txt.setSelectedItem(e);
                        String f=rs.getString("RoomType");
                        type_txt.setSelectedItem(f);
                        String g=rs.getString("CheckIn");
                        ((JTextField)date_1.getDateEditor().getUiComponent()).setText(g);
                        String h=rs.getString("CheckOut");
                        ((JTextField)date_2.getDateEditor().getUiComponent()).setText(h);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, "Sorry No Result");
                    } break;
                }
                default:
                JOptionPane.showMessageDialog(null, "Please Click on Select Field !");
                break;
            }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, "Please Click on Select Field !");
        }
        finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(conn!=null)
                {
                    conn.close();
                }
                if(pst!=null)
                {
                    pst.close();
                }
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null, "Connection not has been closed yet");
            }
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void select_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_select_txtActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        String aa=name_txt.getText();
        String bb=Id_txt.getText();
        if(name_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Customer Name !");
        }
        else if(Id_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter ID(Must not Unique) !");
        }
        else if(mobile_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Mobile Number !");
        }
        else if(Profession_txt.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Profession !");
        }
        else if(romm_txt.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Room !");
        }
        else if(type_txt.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Select Room Type!");
        }
        else if(((JTextField)date_1.getDateEditor().getUiComponent()).getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Choose Date !");
        }
        else if(((JTextField)date_2.getDateEditor().getUiComponent()).getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Choose Date !");
        }
        else
        {
            try
            {
                String sql="insert into Customer_Bill values(?,?,?,?,?,?,?,?,?)";
                pst=conn.prepareStatement(sql);
                pst.setString(1, name_txt.getText());
                pst.setString(2, Id_txt.getText());
                pst.setString(3, mobile_txt.getText());
                pst.setString(4, Profession_txt.getText());
                pst.setString(5, romm_txt.getSelectedItem().toString());
                pst.setString(6, type_txt.getSelectedItem().toString());
                pst.setString(7, ((JTextField)date_1.getDateEditor().getUiComponent()).getText());
                pst.setString(8, ((JTextField)date_2.getDateEditor().getUiComponent()).getText());
                pst.setString(9, total.getText());
                int p=JOptionPane.showConfirmDialog(null,"Do you want to save","Conform Save",JOptionPane.YES_NO_OPTION);
                if(p==0)
                {
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Saved");

                 
                   
                }
            }
            catch(HeadlessException | SQLException ex)
            {
                JOptionPane.showMessageDialog(null, "sorry Error Occured\n"+ex);
            }
            finally
            {
                try
                {
                    if(rs!=null)
                    {
                        rs.close();

                    }
                    if(conn!=null)
                    {
                        conn.close();
                    }
                    if(pst!=null)
                    {
                        pst.close();
                    }
                }
                catch(SQLException e)
                {
                    JOptionPane.showMessageDialog(null, "Connection not has been closed yet");
                }
            }
        }

    }//GEN-LAST:event_save_btnActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        new Printing(Id_txt.getText()).setVisible(true);
        dispose();
    }//GEN-LAST:event_printActionPerformed

    private void Back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_btnActionPerformed
        // TODO add your handling code here:
        new Registration().setVisible(true);
        dispose();
    }//GEN-LAST:event_Back_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_btn;
    private javax.swing.JTextField Id_txt;
    private javax.swing.JTextField Profession_txt;
    private com.toedter.calendar.JDateChooser date_1;
    private com.toedter.calendar.JDateChooser date_2;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobile_txt;
    private javax.swing.JTextField name_txt;
    private javax.swing.JButton print;
    private javax.swing.JComboBox<String> romm_txt;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_txt;
    private javax.swing.JComboBox<String> select_txt;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<String> type_txt;
    // End of variables declaration//GEN-END:variables
}
