
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rudr'a
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
        this.setResizable(false);
        setIcon();
    }
public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("HotelIcon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Check_pass = new javax.swing.JCheckBox();
        save_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        Re_Enter = new javax.swing.JPasswordField();
        Exist_pass = new javax.swing.JPasswordField();
        new_pass = new javax.swing.JPasswordField();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Password");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Re-Enter");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 30));

        user_name.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 280, 30));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("User Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 30));

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel8.setText("Exist Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, 30));

        jLabel9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel9.setText("New Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 30));

        Check_pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Check_pass.setForeground(new java.awt.Color(255, 255, 255));
        Check_pass.setText("Show Password");
        Check_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_passActionPerformed(evt);
            }
        });
        getContentPane().add(Check_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 220, 30));

        save_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Opened Folder_48px.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.setBorder(null);
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(save_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 110, 30));

        close_btn.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        close_btn.setText("Close");
        close_btn.setBorder(null);
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 90, 30));

        Re_Enter.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(Re_Enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 270, 30));

        Exist_pass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(Exist_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 270, 30));

        new_pass.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        getContentPane().add(new_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 270, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/497320.jpg"))); // NOI18N
        image.setText("jLabel1");
        getContentPane().add(image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Check_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_passActionPerformed
        // TODO add your handling code here:
       if(Check_pass.isSelected())
        {
            Exist_pass.setEchoChar((char)0);
            new_pass.setEchoChar((char)0);
            Re_Enter.setEchoChar((char)0);
        }
        else
        {
            Exist_pass.setEchoChar('*');
            new_pass.setEchoChar('*');
            Re_Enter.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_passActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        String Epass=Exist_pass.getText();
        String Npass=new_pass.getText();
        String Cpass=Re_Enter.getText();
       Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        try
        {

            if(Exist_pass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Fill Exist Password !");

            }
            else  if(new_pass.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Fill New Password Password !");

            }
            else  if(Re_Enter.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Fill Conform Password !");

            }
            else
            {
                //String a=rs.getString("user_id");
                if(new_pass.getText().equals(Re_Enter.getText()))
                {
                    
                    String sql="update Login set Password='"+Cpass+"' where User_Name='"+user_name.getText()+"'";

                    pst=conn.prepareStatement(sql);
                    int C=JOptionPane.showConfirmDialog(null,"Do you want to Really Save?","Conform Save",JOptionPane.YES_NO_OPTION);
                    if(C==0)
                    {
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Update Successfully");
                        user_name.setText("");
                        Exist_pass.setText("");
                        new_pass.setText("");
                        Re_Enter.setText("");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Password not Match");
                }
            }
        }
        catch(HeadlessException | SQLException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        new Login_Window().setVisible(true);
        dispose();
    }//GEN-LAST:event_close_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Check_pass;
    private javax.swing.JPasswordField Exist_pass;
    private javax.swing.JPasswordField Re_Enter;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField new_pass;
    private javax.swing.JButton save_btn;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
