
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rudr'a
 */
public class Login_Window extends javax.swing.JFrame {

    /**
     * Creates new form Login_Window
     */
    public Login_Window() {
           this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        initComponents();
        setIcon();
    }
    public void setIcon()
    {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("HotelIcon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator6 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Admin_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        Password_txt = new javax.swing.JPasswordField();
        Check_pass = new javax.swing.JCheckBox();
        LOGIN = new javax.swing.JButton();
        HELP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log IN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 420, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setAlignmentX(1.0F);
        jSeparator4.setAlignmentY(1.0F);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 90, 10, 420));

        Admin_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Admin_txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Admin_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 290, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_48px.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 50, 50));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 10, 420));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 420, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Password_48px.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, 50, 50));

        Password_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password_txt.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(Password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 290, 30));

        Check_pass.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        Check_pass.setForeground(new java.awt.Color(255, 255, 255));
        Check_pass.setText("Show Password");
        Check_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Check_passActionPerformed(evt);
            }
        });
        getContentPane().add(Check_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 190, -1));

        LOGIN.setBackground(new java.awt.Color(0, 153, 0));
        LOGIN.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 255, 255));
        LOGIN.setText("Log IN");
        LOGIN.setBorder(null);
        LOGIN.setOpaque(false);
        LOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGINActionPerformed(evt);
            }
        });
        getContentPane().add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, 90, 30));

        HELP.setBackground(new java.awt.Color(255, 0, 0));
        HELP.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        HELP.setForeground(new java.awt.Color(255, 255, 255));
        HELP.setText("Help");
        HELP.setBorder(null);
        HELP.setOpaque(false);
        HELP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HELPActionPerformed(evt);
            }
        });
        getContentPane().add(HELP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 90, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Log IN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 110, 140, 40));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 48)); // NOI18N
        jLabel1.setText("Priyanka Palace");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 460, 60));

        jLabel4.setFont(new java.awt.Font("Viner Hand ITC", 3, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Hotel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 150, 60));

        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/497320.jpg"))); // NOI18N
        getContentPane().add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Check_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Check_passActionPerformed
        // TODO add your handling code here:
        if(Check_pass.isSelected())
        {
            Password_txt.setEchoChar((char)0);
        }
        else
        {
            Password_txt.setEchoChar('*');
        }
    }//GEN-LAST:event_Check_passActionPerformed

    private void LOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGINActionPerformed
        // TODO add your handling code here:
        String Update_date=null;

        Connection conn=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        conn=JavaConnect.ConnectDB();
        String sql="select * from Login where User_Name=? and Password=?";
        try
        {
            String st=Admin_txt.getText();
            String st2=Password_txt.getText();
          
            if(st.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "User Name is Empty");

            }
            else if(st2.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Password is Empty");
            }
           
            else
            {
                pst=conn.prepareStatement(sql);
                pst.setString(1,Admin_txt.getText());
                pst.setString(2,Password_txt.getText());
                rs=pst.executeQuery();
                if(rs.next())
                {

                
                    new Registration().setVisible(true);
                    dispose();
                }

                else
                {
                    JOptionPane.showMessageDialog(null,"Login_Name and passwoed is not correct");
                    Admin_txt.setText("");
                    Password_txt.setText("");
                }
            }
        }
        catch(HeadlessException | SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        finally
        {
            try
            {
                if(rs!=null)
                {
                    rs.close();

                }
                if(pst!=null)
                {
                    pst.close();
                }
                if(conn!=null)
                {
                    conn.close();
                }
            }
            catch(SQLException ex)
            {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_LOGINActionPerformed

    private void HELPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HELPActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "If you Forget your password, then contact Administrative\n\t\tMiss. Rupali Johare\n\t\te-mail. rupalijohare3@gmail.com");
    }//GEN-LAST:event_HELPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admin_txt;
    private javax.swing.JCheckBox Check_pass;
    private javax.swing.JButton HELP;
    private javax.swing.JLabel Image;
    private javax.swing.JButton LOGIN;
    private javax.swing.JPasswordField Password_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
